fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.12.1
    provision: 'https://github.com/puppetlabs/provision.git'
  forge_modules:
    pwshlib: "puppetlabs/pwshlib"
  symlinks:
    "powershell": "#{source_dir}"
