---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
  selected_profile: false
".travis.yml":
  simplecov: true
  os:
    - linux
    - osx
  before_install_pre:
    - bash <(curl -s https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh) -skip-sudo-check
    - 'pwsh -NoProfile -NoLogo -NonInteractive -Command \$PSVersionTable # Output the PowerShell Core version information'
    - if [ $BUNDLER_VERSION ]; then
        gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
      fi
appveyor.yml:
  unmanaged: true
Gemfile:
  optional:
    ":development":
    - gem: ruby-pwsh
  required:	
    ':system_tests':	
      - gem: 'puppet-module-posix-system-r#{minor_version}'	
        platforms: ruby	
      - gem: 'puppet-module-win-system-r#{minor_version}'	
        platforms:	
          - mswin	
          - mingw	
          - x64_mingw	
      - gem: beaker-testmode_switcher	
        version: '~> 0.4'	
      - gem: master_manipulator	
      - gem: puppet-blacksmith	
        version: '~> 3.4'
spec/spec_helper.rb:
  coverage_report: true
