---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  selected_profile: false
  include_todos: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: ruby-pwsh
  overrides:
    - gem: 'puppetlabs_spec_helper'
      version: '~> 9.0'
    - gem: 'puppet_litmus'
      version: '~> 2.8'
spec/spec_helper.rb:
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: true
  acceptance_flags:
    - '--nightly'
    - '--arch-exclude arm'
    - '--collection-platform-exclude 9:centos-7'
    - '--collection-platform-exclude 9:redhat-7'
    - '--collection-platform-exclude 9:debian-10'
    - '--collection-platform-exclude 9:ubuntu-20.04'
.github/workflows/nightly.yml:
  unmanaged: true
  acceptance_flags:
    - '--nightly'
    - '--arch-exclude arm'
    - '--collection-platform-exclude 9:centos-7'
    - '--collection-platform-exclude 9:redhat-7'
    - '--collection-platform-exclude 9:debian-10'
    - '--collection-platform-exclude 9:ubuntu-20.04'
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
