name    'joshcooper-powershell'
version '0.0.1'
source 'git://github.com/joshcooper/powershell.git'
author 'Josh Cooper'
license 'Apache License, Version 2.0'
summary 'A powershell provider for puppet.'
description 'A powershell provider for puppet.'
project_page 'http://links.puppetlabs.com/powershellb-module'
