name    'joshcooper-powershell'
version '0.0.6'
source 'git://github.com/joshcooper/puppetlabs-powershell.git'
author 'Josh Cooper'
license 'Apache License, Version 2.0'
summary 'A PowerShell provider for puppet.'
description 'A PowerShell provider for puppet.'
project_page 'http://links.puppetlabs.com/powershell-module'
