name: "nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    with:
      additional_packages: "libcurl4-openssl-dev"
      ruby_version: "3.2"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    with:
      flags: "--nightly --arch-exclude arm --collection-platform-exclude 9:centos-7 --collection-platform-exclude 9:redhat-7 --collection-platform-exclude 9:debian-10 --collection-platform-exclude 9:ubuntu-20.04"
      ruby_version: "3.2"
    secrets: "inherit"
